---
# h1 page title on top of the page
title: Title
# h2 subtitle below h1
subtitle: Subtitle
# label for the submit button
submit: Submit
# now configure as many form fields as you like
# supported types are: rating, text, textarea (see following examples)
# type and title are mandatory for every field
fields:
# rating with multiple stars
- type: rating                  # input type, mandatory
  title: Overall Satisfaction   # field title, shown in Telegram message result, mandatory
  label: How satisfied are you? # field lable, shown on the web form
  precision: 0.5                # let users select fractional ratings
  max: 5                        # max rating value, number of stars
  required: false               # indicate required input
# single line text input
- type: text                    # input type, mandatory
  title: To improve             # field title, shown in Telegram message result, mandatory
  label: This should be better  # field lable, shown on the web form
  placeholder: Something bad    # field placeholder
  required: false               # indicate required text input
# multi line text input
- type: textarea                # input type, mandatory
  title: To keep                # field title, shown in Telegram message result, mandatory
  label: This is awesome        # field lable, shown on the web form
  placeholder: Something good   # field placeholder
  maxlength: 1000               # maximum length of valid input
  required: false               # indicate required text input
